### ISSUE TITLE
Scaling issue 

### ISSUE THREAD

**Issue by unicornsandcandies** [midnightgospel/SD-Themes#1]
After today's update my custom gif is much smaller. It's replacing the original but it seems like the scaling toggles are broken because they're not doing anything, no matter what setting. It's always stretched into default animation dimensions in ugly way

**Comment by midnightgospel** [comment]
I will look into this. I currently have Windows on my Deck, but I will try to get this fixed as soon as I can. Thank you for the heads up.

**Comment by midnightgospel** [comment]
Issue confirmed. Working on it now.

**Comment by midnightgospel** [comment]
Issue fixed. Update is being uploaded to the store and should be available as soon as it's approved. Keep an eye out for an update as I don't think they auto update.
