### ISSUE TITLE
Question not sure if issue or not

### ISSUE THREAD

**Issue by Sammmy1036** [midnightgospel/SD-Themes#4]
When placing gifs 250x250 or even 240x240 like recommended they do not show up when selecting custom images. Is there a step needed after placing custom gifs in the images folder?

**Comment by midnightgospel** [comment]
As long as the files are in there or in the theme folder, you should be able to find the image with the file browser. I haven't really changed mine in awhile. Might be something wrong with the latest update. Ensure your CSS Loader plugin is up to date and so is Decky. I'll look into it today. I need to fix an issue I found with one of the defaults as well. Also, what SteamOS are you on?

**Comment by Sammmy1036** [comment]
It’s running below: 
OS Name: SteamOS Holo
OS Version: 3.4.8
OS Build: 20230508.1

**Comment by midnightgospel** [comment]
Well same version here and I was able to take a random gif and load it up. Are you by any chance in the DeckThemes discord?

**Comment by Sammmy1036** [comment]
Yes I am in that server.

**Comment by midnightgospel** [comment]
Shoot me a message on there or DM me and we'll get this figured out 👍🏻. Same username
