### ISSUE TITLE
fullscreen

### ISSUE THREAD

**Issue by Kazlehoff** [midnightgospel/SD-Themes#5]
i have a 1280x800 gif i want to play full screen via custom loader. What would be best to accomplish this?

**Comment by midnightgospel** [comment]
if you have a link to the GIF, I can take a look and make a possible edit to the theme if I can't get it with standard settings. not sure i ever tried a full size GIF because of the quality haha. or i guess you can attach the GIF here as well.

**Comment by Kazlehoff** [comment]
![ezgif-3-2850d9d0aa](https://github.com/midnightgospel/SD-Themes/assets/52207847/3dda95c9-e766-4b4d-a525-e6bd1e5b449e)

**Comment by midnightgospel** [comment]
Awesome. Let me play around with this a little bit and I'll get you a result soon 👍🏻

**Comment by Kazlehoff** [comment]
Hiya.


Very much appreciated. The GIF is just the old Windows 3.1 era star field (lol) screensaver.

It's odd, because when I added the GIF to the deck, it showed up tiny. Even with the size setting to max.

When, however, I used the included labs GIF, it showed up much larger, despite it being a smaller GIF.

Even just larger size options would be a pretty good option. i tried to add additional sizes by copy/paste from the largest size, and simply increasing the pix setting, but when done, the theme disappears from the list (ie: no longer recognized as working) made sure i had copied the open and close brackets and everything, as confirmed through notepad++

once that failed, i came to ask you about it. :D

**Comment by midnightgospel** [comment]
Haha sounds good. I’ll take a look when I return from traveling as I didn’t bring my steam deck on this trip. Sadly it doesn’t play Starfield very well. So laptop it was xDOn Sep 20, 2023, at 9:35 AM, tacOS ***@***.***> wrote:﻿
Hiya.
Very much appreciated. The GIF is just the old Windows 3.1 era star field (lol) screensaver.
It's odd, because when I added the GIF to the deck, it showed up tiny. Even with the size setting to max.
When, however, I used the included labs GIF, it showed up much larger, despite it being a smaller GIF.
Even just larger size options would be a pretty good option. i tried to add additional sizes by copy/paste from the largest size, and simply increasing the pix setting, but when done, the theme disappears from the list (ie: no longer recognized as working) made sure i had copied the open and close brackets and everything, as confirmed through notepad++
once that failed, i came to ask you about it. :D

**Comment by midnightgospel** [comment]
Ok I believe it's fixed, only thing I need to figure out now though is I'm seeing a black bar where the nav bar usually is at the bottom. Not sure what that is all about, but I'm working on it.

Edit: Nvm I'm an idiot. It's working now. I will push the update to Deck Themes.

**Comment by Kazlehoff** [comment]
:O 

Dude, Rad ^__^, thank you, i'll try it out after dinner!

**Comment by Kazlehoff** [comment]
Just tried it... let me get a picture.
![PXL_20230927_220449794](https://github.com/midnightgospel/SD-Themes/assets/52207847/cfd53b68-dfa6-449a-b7bd-35108d91cd94)

this is both by downloading in CSS loader, and directly downloading the files from github and manually copying over.

also confirming that fullscreen option was ticked.

edit: tried with another GIF as well, same issue

**Comment by Kazlehoff** [comment]
sorry, wrong button. apologies.

**Comment by midnightgospel** [comment]
With the new .json on GitHub, this should add the fullscreen toggle above image size. If you don’t see that, try pressing refresh at the bottom of CSS loader. On Sep 27, 2023, at 6:11 PM, tacOS ***@***.***> wrote:﻿
Reopened #5.

**Comment by Kazlehoff** [comment]
fullscreen toggle ticked. plugin downloaded from both the repo, and here from github directly. tried with both the GIF linked above, and another downloaded from imgur.

**Comment by Kazlehoff** [comment]
Oh, Just to be sure, i also disabled every other plugin in CSS loader, no dice. 

None of my plugins outside of CSS loader interact with the loading screen. Animation changer (only does Throbber, boot, and suspend screens), Audio loader, AutoFlatpacks, Bluetooth, Discord Status, MangoPeel, Powertools, VibrantDeck, SteamGridDB, and ofc CSS Loader.

**Comment by midnightgospel** [comment]
Can you try deleting the theme, and reinstalling it from GitHub? Here's some photos of it working on my end.
![20230928_000202765_iOS](https://github.com/midnightgospel/SD-Themes/assets/25554881/b9020fb0-3e90-4079-b4ec-b3ff97055ba4)
![20230928_000209534_iOS](https://github.com/midnightgospel/SD-Themes/assets/25554881/2eb981ec-b343-4cc6-934b-f6731433efaf)
![20230928_000214976_iOS](https://github.com/midnightgospel/SD-Themes/assets/25554881/4b32a25c-3522-4ac7-8366-6f35f617f2e7)
![20230928_000219540_iOS](https://github.com/midnightgospel/SD-Themes/assets/25554881/87961ce2-a02c-483b-abbe-2e893ca5c895)
![20230928_000459834_iOS](https://github.com/midnightgospel/SD-Themes/assets/25554881/f4bcc7cc-7447-49ce-b2a6-22bed1b669d9)

**Comment by Kazlehoff** [comment]
the version on the CSS loader store is still 1.2.1, so i had to  re-downloiad from the repo here.

i don tknow what would have changed, but it's now working as expected... odd. 

thanks very much :)

**Comment by midnightgospel** [comment]
I pushed the update to the crew at Deck Themes. Just have to wait for the official update to be approved. So you're going to see your Custom Loader be out of date until then. Just don't update it and you should be good.
